/**
 * Build script — single source of truth for the Sojurno v2 design system.
 *
 *   DTCG JSON (primitives + base semantic + per-tenant overrides)
 *        ─▶  src/styles/_tokens.scss   (consumed by the Tailwind v4 @theme inline
 *                                        bridge in src/styles/tailwind.css)
 *
 * Layers share one primitive palette and re-point the same --color-* names:
 *   • :root                              ← primitives + base LIGHT semantic
 *   • [data-theme=dark]                  ← base DARK semantic
 *   • [data-tenant=T]                    ← tenant LIGHT brand overrides (accent)
 *   • [data-tenant=T][data-theme=dark]   ← tenant DARK overrides (from *.dark.json)
 *
 * Tenant overrides carry only the brand-identity colors; everything else
 * cascades from the base. `[data-tenant][data-theme]` outranks `[data-theme]`,
 * so tenant × theme composes correctly. Tenants are discovered from
 * tokens/tenants/*.light.json — adding a community is adding data, not code.
 *
 * Output is git-ignored and regenerated by `npm run tokens` (run automatically
 * by dev / build / storybook). Edit the JSON, never the generated SCSS.
 *
 * Note: an explicit transform set (not transformGroup "css") is used so that
 * dimension/shadow/fontFamily string values pass through verbatim.
 */
import StyleDictionary from 'style-dictionary'
import { readFileSync, writeFileSync, rmSync, readdirSync, existsSync } from 'node:fs'

const PRIMITIVES = 'tokens/primitives.json'
const TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css']
const onlyFrom = (fileName) => (token) => token.filePath.includes(fileName)

/** One Style Dictionary pass → returns the generated CSS as a string. */
async function buildCss({ name, sources, selector, filter }) {
  const dest = `_tokens.${name}.gen.css`
  const sd = new StyleDictionary({
    source: sources,
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transforms: TRANSFORMS,
        buildPath: 'src/styles/',
        files: [
          {
            destination: dest,
            format: 'css/variables',
            filter,
            options: { selector, outputReferences: true, showFileHeader: false },
          },
        ],
      },
    },
  })
  await sd.buildAllPlatforms()
  const path = `src/styles/${dest}`
  const css = readFileSync(path, 'utf8')
  rmSync(path)
  return css
}

// Discover tenants from their light override files.
const tenants = readdirSync('tokens/tenants')
  .filter((f) => f.endsWith('.light.json'))
  .map((f) => f.replace('.light.json', ''))

const blocks = []

// Base: :root (primitives + light semantic) and [data-theme=dark] (dark only).
blocks.push(
  await buildCss({
    name: 'light',
    sources: [PRIMITIVES, 'tokens/semantic.light.json'],
    selector: ':root',
  }),
)
blocks.push(
  await buildCss({
    name: 'dark',
    sources: [PRIMITIVES, 'tokens/semantic.dark.json'],
    selector: '[data-theme="dark"]',
    filter: onlyFrom('semantic.dark.json'),
  }),
)

// Per-tenant brand overrides, scoped by attribute. Each tenant emits its LIGHT
// block ([data-tenant=T]); tenants with a *.dark.json also emit a DARK block
// ([data-tenant=T][data-theme=dark], higher specificity) so tenant × theme
// composes — e.g. accent-soft becomes a translucent tint that works on dark.
for (const t of tenants) {
  blocks.push(
    await buildCss({
      name: `${t}.light`,
      sources: [PRIMITIVES, `tokens/tenants/${t}.light.json`],
      selector: `[data-tenant="${t}"]`,
      filter: onlyFrom(`${t}.light.json`),
    }),
  )
  if (existsSync(`tokens/tenants/${t}.dark.json`)) {
    blocks.push(
      await buildCss({
        name: `${t}.dark`,
        sources: [PRIMITIVES, `tokens/tenants/${t}.dark.json`],
        // Two forms so the dark tint wins whether data-tenant is on the same
        // element as data-theme (root, via TenantProvider) or on a nested
        // element (e.g. a section that re-declares data-tenant locally).
        selector: `[data-tenant="${t}"][data-theme="dark"], [data-theme="dark"] [data-tenant="${t}"]`,
        filter: onlyFrom(`${t}.dark.json`),
      }),
    )
  }
}

const header = `/* AUTO-GENERATED by tokens/build-tokens.mjs — do not edit by hand.
   Edit tokens/*.json, then run \`npm run tokens\`. */\n\n`
writeFileSync('src/styles/_tokens.scss', header + blocks.join('\n'))
console.log(`✓ _tokens.scss generated (${tenants.length} tenants: ${tenants.join(', ')})`)
