/**
 * Build-time export (ADR-0022, promotes ADR-0017).
 *
 * Pulls `published` + generated rows from Supabase and writes them to
 * `src/data/listings.generated.ts` as a typed `Listing[]`. The app reads this committed file at
 * build time (no runtime DB dependency) — see src/data/listings.ts (the seam).
 *
 * Run after generating (`npm run gen:listings`), then COMMIT the generated file:
 *   npm run export:listings
 */
import 'dotenv/config'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createClient } from '@supabase/supabase-js'
import type { Listing } from '../src/types'

const OUT = resolve(process.cwd(), 'src/data/listings.generated.ts')

function requireEnv(name: string): string {
  const v = process.env[name]
  if (!v) {
    console.error(`✖ Missing ${name} — copy .env.example to .env and fill it in.`)
    process.exit(1)
  }
  return v
}

/** DB row (snake_case) → app `Listing` (camelCase), dropping null optionals. */
function toListing(row: Record<string, unknown>): Listing {
  const listing: Listing = {
    id: String(row.id),
    tenant: row.tenant_id as Listing['tenant'],
    bookingMode: row.booking_mode as Listing['bookingMode'],
    title: String(row.title),
    location: String(row.location),
    neighborhood: String(row.neighborhood),
    price: Number(row.price),
    rating: Number(row.rating),
    reviewCount: Number(row.review_count),
    host: row.host as Listing['host'],
    images: (row.images as Listing['images']) ?? [],
    tags: (row.tags as string[]) ?? [],
    amenities: (row.amenities as string[]) ?? [],
    highlight: String(row.highlight),
    description: String(row.description),
  }
  if (row.external_url) listing.externalUrl = String(row.external_url)
  if (row.gear) listing.gear = row.gear as Listing['gear']
  return listing
}

async function main() {
  const supabase = createClient(requireEnv('SUPABASE_URL'), requireEnv('SUPABASE_SERVICE_ROLE_KEY'))

  // Only the curated seed + generated rows are baked into the static export. User-created rows
  // (source='user', ADR-0026) are the live runtime overlay and must NOT be committed here.
  const { data, error } = await supabase
    .from('listings')
    .select('*')
    .eq('status', 'published')
    .in('source', ['seed', 'generated'])
    .order('created_at', { ascending: true })
  if (error) throw error

  const listings = (data ?? []).map(toListing)
  const banner =
    '// AUTO-GENERATED by `npm run export:listings` (ADR-0022). DO NOT EDIT BY HAND.\n' +
    `// Source: Supabase \`listings\` (status=published — seed + generated). ${listings.length} row(s).\n`
  const body =
    `import type { Listing } from '../types'\n\n` +
    `export const DB_LISTINGS: Listing[] = ${JSON.stringify(listings, null, 2)}\n`

  writeFileSync(OUT, `${banner}\n${body}`)
  console.log(`✓ Wrote ${listings.length} listing(s) → ${OUT}`)
}

main().catch((err) => {
  console.error('\n✖ Export failed:', err instanceof Error ? err.message : err)
  process.exit(1)
})
