// AUTO-GENERATED by `npm run export:listings` (ADR-0022). DO NOT EDIT BY HAND.
// Source: Supabase `listings` (status=published, source=generated). 0 row(s).

import type { Listing } from '../types'

export const GENERATED_LISTINGS: Listing[] = []
