// AUTO-GENERATED by `npm run export:listings` (ADR-0022). DO NOT EDIT BY HAND.
// Source: Supabase `listings` (status=published — seed + generated). 29 row(s).

import type { Listing } from '../types'

export const DB_LISTINGS: Listing[] = [
  {
    "id": "back-bay-split",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Back Bay brownstone two blocks from the marathon buses",
    "location": "Boston, MA",
    "neighborhood": "Back Bay",
    "price": 214,
    "rating": 4.98,
    "reviewCount": 86,
    "host": {
      "bio": "Boston local, pacer, and expert in race-week logistics from shakeout routes to bag check timing.",
      "name": "Mara",
      "badge": "12 marathons hosted",
      "avatar": "MR",
      "avatarUrl": "https://i.pravatar.cc/96?img=47"
    },
    "images": [
      {
        "alt": "Warm living room in a Boston brownstone.",
        "src": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Start-line shuttle",
      "Early breakfast",
      "Foam roller"
    ],
    "amenities": [
      "Flexible race morning checkout",
      "Kitchen stocked for breakfast",
      "Quiet room away from street"
    ],
    "highlight": "The host maps an easy shakeout loop along the Charles before race day.",
    "description": "A calm, polished base for runners who want the city close and race morning made simple. The apartment keeps the practical things easy: breakfast space, quiet sleep, transit guidance, and a host who has done the weekend many times."
  },
  {
    "id": "brooklyn-pacehouse",
    "tenant": "runners",
    "bookingMode": "external",
    "title": "Park Slope pace house near Prospect Park loops",
    "location": "Brooklyn, NY",
    "neighborhood": "Park Slope",
    "price": 188,
    "rating": 4.94,
    "reviewCount": 64,
    "host": {
      "bio": "Club runner who knows Prospect Park, subway timing, and the difference between a jog and a shakeout.",
      "name": "Andre",
      "badge": "NYC running club host",
      "avatar": "AK",
      "avatarUrl": "https://i.pravatar.cc/96?img=12"
    },
    "images": [
      {
        "alt": "Bright Brooklyn townhouse bedroom.",
        "src": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Externally booked",
      "Park loop nearby",
      "Club host"
    ],
    "amenities": [
      "Secure gear corner",
      "Park route notes",
      "Coffee before sunrise"
    ],
    "highlight": "Linked listing: discover through Sojurno, book on the host-owned external page.",
    "description": "A community-vetted runner stay near Prospect Park. This listing is host-owned and booked externally, clearly signposted so the transaction stays where the host already manages it.",
    "externalUrl": "https://www.airbnb.com/"
  },
  {
    "id": "chicago-lakefront",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Lakefront studio built around race-week calm",
    "location": "Chicago, IL",
    "neighborhood": "South Loop",
    "price": 172,
    "rating": 4.96,
    "reviewCount": 72,
    "host": {
      "bio": "Chicago volunteer and runner who knows corrals, trains, lakefront miles, and where to decompress.",
      "name": "Talia",
      "badge": "Course volunteer",
      "avatar": "TS",
      "avatarUrl": "https://i.pravatar.cc/96?img=45"
    },
    "images": [
      {
        "alt": "Minimal studio bedroom with soft morning light.",
        "src": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Transit easy",
      "Course volunteer",
      "Quiet studio"
    ],
    "amenities": [
      "Blackout curtains",
      "Transit notes",
      "Recovery snacks"
    ],
    "highlight": "A quiet South Loop stay with a host who knows the course logistics.",
    "description": "Simple, bright, and quiet enough to protect the taper. The stay is designed for runners who want walkable food, easy trains, and someone local who understands the race-week mental state."
  },
  {
    "id": "sf-crissy-field",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Serene guest suite near Crissy Field trail network",
    "location": "San Francisco, CA",
    "neighborhood": "Marina District",
    "price": 196,
    "rating": 4.95,
    "reviewCount": 52,
    "host": {
      "bio": "Bay Area runner who knows bridge miles, coastal wind, and where to recover after a long morning.",
      "name": "Daniel",
      "badge": "Ultra runner",
      "avatar": "DL",
      "avatarUrl": "https://i.pravatar.cc/96?img=33"
    },
    "images": [
      {
        "alt": "Compact guest suite with a bright kitchen and sitting area.",
        "src": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Trail maps",
      "Pre-dawn kitchen",
      "Recovery nook"
    ],
    "amenities": [
      "Washer for race kit",
      "Bridge route notes",
      "Quiet garden entrance"
    ],
    "highlight": "A calm Marina base for runners mixing road miles, park loops, and coastal trails.",
    "description": "A small, composed guest suite for runners who want early access to Crissy Field, the Presidio, and bridge routes. The host keeps route notes practical and the space quiet after long efforts."
  },
  {
    "id": "austin-east-loop",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "East Austin bungalow steps from the Lady Bird trail",
    "location": "Austin, TX",
    "neighborhood": "East Austin",
    "price": 179,
    "rating": 4.93,
    "reviewCount": 61,
    "host": {
      "bio": "Austin runner who knows the Lady Bird loop, summer heat timing, and the best taco recovery stops.",
      "name": "Priya",
      "badge": "Trail-series host",
      "avatar": "PR",
      "avatarUrl": "https://i.pravatar.cc/96?img=5"
    },
    "images": [
      {
        "alt": "Sunlit bungalow living room with warm wood floors.",
        "src": "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Trail access",
      "Heat-smart timing",
      "Recovery tacos"
    ],
    "amenities": [
      "Pre-dawn coffee",
      "Cold hose for ice baths",
      "Shaded route notes"
    ],
    "highlight": "A host who plans your miles around Austin heat and the Lady Bird loop.",
    "description": "A relaxed East Austin base for runners who want trail access without a car. The host keeps mornings early, hydration easy, and route advice tuned to the season."
  },
  {
    "id": "philly-schuylkill",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Fairmount rowhouse on the Schuylkill river loop",
    "location": "Philadelphia, PA",
    "neighborhood": "Fairmount",
    "price": 165,
    "rating": 4.91,
    "reviewCount": 44,
    "host": {
      "bio": "Philly pacer who runs Kelly Drive daily and knows where the river loop is flattest and quietest.",
      "name": "Marcus",
      "badge": "Marathon pacer",
      "avatar": "MJ",
      "avatarUrl": "https://i.pravatar.cc/96?img=60"
    },
    "images": [
      {
        "alt": "Tidy rowhouse bedroom with soft natural light.",
        "src": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "River loop",
      "Flat miles",
      "Pacer host"
    ],
    "amenities": [
      "Foam roller",
      "Loop distance markers",
      "Quiet street"
    ],
    "highlight": "Step out the door onto the flat, scenic Schuylkill river loop.",
    "description": "A straightforward Fairmount rowhouse for runners who want flat river miles and an easy taper. The host shares pacing notes and keeps the house calm before race morning."
  },
  {
    "id": "whitney-portal-cabin",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "Portal cabin with bear canister and trail beta",
    "location": "Lone Pine, CA",
    "neighborhood": "Whitney Portal",
    "price": 236,
    "rating": 4.99,
    "reviewCount": 91,
    "host": {
      "bio": "Sierra hiker with local permit knowledge, gear to lend, and a habit of leaving coffee ready early.",
      "name": "Elena",
      "badge": "Backcountry host",
      "avatar": "ER",
      "avatarUrl": "https://i.pravatar.cc/96?img=31"
    },
    "images": [
      {
        "alt": "Cabin bedroom near mountain trailheads.",
        "src": "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Gear included",
      "Permit guidance",
      "Trailhead nearby"
    ],
    "amenities": [
      "Pack staging area",
      "Drying hooks",
      "Early trail breakfast"
    ],
    "highlight": "Borrow a bear canister, poles, or GPS without turning your flight into a gear puzzle.",
    "description": "A trail-ready cabin for hikers who need practical support before a big day outside. The host can lend key gear and talk through conditions without making the stay feel like a rental counter.",
    "gear": [
      {
        "id": "poles",
        "icon": "poles",
        "name": "Trekking poles",
        "category": "Trail support",
        "quantity": 2
      },
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      },
      {
        "id": "gps",
        "icon": "gps",
        "name": "Satellite GPS",
        "category": "Navigation",
        "quantity": 1
      },
      {
        "id": "stove",
        "icon": "stove",
        "name": "Compact stove",
        "category": "Camp kitchen",
        "quantity": 1
      }
    ]
  },
  {
    "id": "olympic-rainroom",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "Rainforest room with drying wall and route notes",
    "location": "Port Angeles, WA",
    "neighborhood": "Olympic foothills",
    "price": 198,
    "rating": 4.97,
    "reviewCount": 58,
    "host": {
      "bio": "Olympic Peninsula hiker who tracks weather windows and knows when a backup route is the right call.",
      "name": "Noah",
      "badge": "Search-and-rescue volunteer",
      "avatar": "NP",
      "avatarUrl": "https://i.pravatar.cc/96?img=68"
    },
    "images": [
      {
        "alt": "Wood cabin exterior surrounded by forest.",
        "src": "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Drying wall",
      "Weather beta",
      "Pack storage"
    ],
    "amenities": [
      "Mudroom",
      "Weather updates",
      "Trailhead shuttle notes"
    ],
    "highlight": "A practical base for wet trails, gear drying, and realistic morning decisions.",
    "description": "Built for hikers arriving with wet layers and changing plans. The stay is quiet and warm, with a host who can help turn a forecast into a sensible route.",
    "gear": [
      {
        "id": "poles",
        "icon": "poles",
        "name": "Trekking poles",
        "category": "Trail support",
        "quantity": 2
      },
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      },
      {
        "id": "gps",
        "icon": "gps",
        "name": "Satellite GPS",
        "category": "Navigation",
        "quantity": 1
      }
    ]
  },
  {
    "id": "glacier-linked",
    "tenant": "hikers",
    "bookingMode": "external",
    "title": "West Glacier bunkhouse linked from a local trail host",
    "location": "West Glacier, MT",
    "neighborhood": "Park entrance",
    "price": 221,
    "rating": 4.92,
    "reviewCount": 47,
    "host": {
      "bio": "Long-distance hiker and local host who keeps route notes current through shoulder season.",
      "name": "Mae",
      "badge": "Trail community host",
      "avatar": "ML",
      "avatarUrl": "https://i.pravatar.cc/96?img=16"
    },
    "images": [
      {
        "alt": "Cozy house patio with mountain view.",
        "src": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Externally booked",
      "Park access",
      "Local beta"
    ],
    "amenities": [
      "Route notes",
      "Boot storage",
      "Bear safety guidance"
    ],
    "highlight": "This host links their existing stay while keeping the affinity context on Sojurno.",
    "description": "A linked hiker stay for travelers who want the community trust layer but will complete booking on the host-owned external listing.",
    "externalUrl": "https://www.airbnb.com/"
  },
  {
    "id": "north-fork-cabin",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "North Fork cabin gateway to Glacier NP trails",
    "location": "West Glacier, MT",
    "neighborhood": "North Fork",
    "price": 211,
    "rating": 4.94,
    "reviewCount": 37,
    "host": {
      "bio": "Seasonal guide with a practical eye for trail closures, shuttle timing, and bear country basics.",
      "name": "Lily",
      "badge": "Glacier guide",
      "avatar": "LC",
      "avatarUrl": "https://i.pravatar.cc/96?img=20"
    },
    "images": [
      {
        "alt": "Mountain cabin near a lake and forested trails.",
        "src": "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Bear country prep",
      "Shuttle advice",
      "Trail closure notes"
    ],
    "amenities": [
      "Bear spray guidance",
      "Boot drying space",
      "Early coffee setup"
    ],
    "highlight": "A low-key cabin with current trail notes and a host who knows when plans need to change.",
    "description": "A practical Glacier base for hikers who need local judgment as much as a bed. The cabin keeps mornings simple, with room for packs, boot drying, and direct advice before the day gets moving.",
    "gear": [
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      },
      {
        "id": "gps",
        "icon": "gps",
        "name": "Satellite GPS",
        "category": "Navigation",
        "quantity": 1
      },
      {
        "id": "stove",
        "icon": "stove",
        "name": "Compact stove",
        "category": "Camp kitchen",
        "quantity": 1
      }
    ]
  },
  {
    "id": "bend-cascade-loft",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "Cascade loft with gear wall near Bend trailheads",
    "location": "Bend, OR",
    "neighborhood": "Old Mill",
    "price": 205,
    "rating": 4.95,
    "reviewCount": 53,
    "host": {
      "bio": "Bend hiker who tracks snow lines, alpine windows, and which lakes are worth the early start.",
      "name": "Sage",
      "badge": "Cascade trail host",
      "avatar": "SW",
      "avatarUrl": "https://i.pravatar.cc/96?img=53"
    },
    "images": [
      {
        "alt": "Cabin loft interior with large windows facing forest.",
        "src": "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Gear wall",
      "Snow-line beta",
      "Early starts"
    ],
    "amenities": [
      "Pack staging",
      "Trail snack pantry",
      "Boot drying rack"
    ],
    "highlight": "Borrow poles or a canister and get current snow-line notes before heading up.",
    "description": "A bright loft for hikers basing out of Bend. The host lends key gear and keeps alpine timing realistic, so big days start prepared instead of guessing.",
    "gear": [
      {
        "id": "poles",
        "icon": "poles",
        "name": "Trekking poles",
        "category": "Trail support",
        "quantity": 2
      },
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      },
      {
        "id": "gps",
        "icon": "gps",
        "name": "Satellite GPS",
        "category": "Navigation",
        "quantity": 1
      },
      {
        "id": "stove",
        "icon": "stove",
        "name": "Compact stove",
        "category": "Camp kitchen",
        "quantity": 1
      }
    ]
  },
  {
    "id": "asheville-blue-ridge",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "Blue Ridge cabin with drying porch near the parkway",
    "location": "Asheville, NC",
    "neighborhood": "West Asheville",
    "price": 189,
    "rating": 4.93,
    "reviewCount": 39,
    "host": {
      "bio": "Blue Ridge hiker who knows parkway closures, fog windows, and the quiet approaches to busy summits.",
      "name": "Jonah",
      "badge": "Appalachian trail host",
      "avatar": "JB",
      "avatarUrl": "https://i.pravatar.cc/96?img=54"
    },
    "images": [
      {
        "alt": "Wooden cabin nestled among forested hills.",
        "src": "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&h=900&fit=crop&auto=format&q=82"
      }
    ],
    "tags": [
      "Parkway access",
      "Fog beta",
      "Quiet approaches"
    ],
    "amenities": [
      "Covered drying porch",
      "Trail maps",
      "Early breakfast"
    ],
    "highlight": "A host who routes you around parkway fog and the crowded summit hours.",
    "description": "A calm Blue Ridge cabin for hikers who want parkway access and local judgment on weather. The drying porch and early breakfast keep multi-day plans simple.",
    "gear": [
      {
        "id": "gps",
        "icon": "gps",
        "name": "Satellite GPS",
        "category": "Navigation",
        "quantity": 1
      },
      {
        "id": "stove",
        "icon": "stove",
        "name": "Compact stove",
        "category": "Camp kitchen",
        "quantity": 1
      }
    ]
  },
  {
    "id": "houston-tx-cozy-retreat-k5g2",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Heights apartment steps from marathon shakeout runs",
    "location": "Houston, TX",
    "neighborhood": "The Heights",
    "price": 180,
    "rating": 4.97,
    "reviewCount": 44,
    "host": {
      "bio": "A local certified coach with a passion for the Houston racing scene and deep knowledge of the best routes.",
      "name": "Clara",
      "badge": "Certified Running Coach",
      "avatar": "C",
      "avatarUrl": "https://i.pravatar.cc/96?img=22"
    },
    "images": [
      {
        "alt": "Cozy Retreat Near the Houston Marathon Route — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/runners/houston-tx-cozy-retreat-k5g2-0.png"
      }
    ],
    "tags": [
      "Marathon-Savvy",
      "Trainer Host",
      "Peaceful Stay"
    ],
    "amenities": [
      "Quiet workspace",
      "Treadmill",
      "Kitchen equipped for meal prep"
    ],
    "highlight": "Just steps from the official marathon shakeout runs and resting spots.",
    "description": "Just a short walk from the official marathon shakeout runs and relaxation spots, this apartment provides a practical base for runners preparing for the Houston Marathon. Your host, Clara, a certified running coach, is on hand to offer valuable insights into race logistics and recommend local pasta restaurants for your carb-loading needs."
  },
  {
    "id": "san-francisco-ca-cozy-retreat-chih",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Sunset District apartment steps from Lake Merced running routes",
    "location": "San Francisco, CA",
    "neighborhood": "Sunset District",
    "price": 220,
    "rating": 4.93,
    "reviewCount": 42,
    "host": {
      "bio": "An avid runner and local marathon coach, I’m here to ensure your race week goes smoothly.",
      "name": "Maya",
      "badge": "Marathon coach",
      "avatar": "M",
      "avatarUrl": "https://i.pravatar.cc/96?img=69"
    },
    "images": [
      {
        "alt": "Cozy Retreat Near Lake Merced for Runners — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/runners/san-francisco-ca-cozy-retreat-chih-0.png"
      }
    ],
    "tags": [
      "Distance Runners",
      "Marathon Ready",
      "Cozy Stay"
    ],
    "amenities": [
      "Quiet space",
      "Access to bathroom essentials",
      "Private kitchen"
    ],
    "highlight": "Just a short run to Golden Gate Park and the marathon start line.",
    "description": "This Sunset District apartment puts you steps from the scenic trails around Lake Merced, ideal for those planning race day training. With straightforward access to Golden Gate Park and public transit, you can rely on your host for insights into race logistics and tailored running routes to maximize your preparation."
  },
  {
    "id": "chicago-il-comfortable-haven-36m2",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Lincoln Park apartment steps from the Lakefront Trail",
    "location": "Chicago, IL",
    "neighborhood": "Lincoln Park",
    "price": 210,
    "rating": 4.96,
    "reviewCount": 59,
    "host": {
      "bio": "I love guiding fellow runners to the best paths and post-race eateries in the city.",
      "name": "Maya",
      "badge": "Experienced Marathoner",
      "avatar": "M",
      "avatarUrl": "https://i.pravatar.cc/96?img=41"
    },
    "images": [
      {
        "alt": "Comfortable Haven for Runners Near Lakefront Trail — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/runners/chicago-il-comfortable-haven-36m2-0.png"
      }
    ],
    "tags": [
      "Running Friendly",
      "Local Insights",
      "Comfy Retreat"
    ],
    "amenities": [
      "Access to running gear",
      "Recovery tools",
      "Nearby transit access"
    ],
    "highlight": "Enjoy a scenic warm-up on the Lakefront Trail, just blocks away.",
    "description": "Just a few blocks from the Lakefront Trail, this apartment offers a practical base for runners preparing for the Chicago marathon. With helpful insights from a host familiar with the area and local spots for post-race recovery, you'll have all you need to focus on your training or tapering without distraction."
  },
  {
    "id": "boston-ma-comfortable-retreat-kabz",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Jamaica Plain apartment with quick access to Emerald Necklace trails",
    "location": "Boston, MA",
    "neighborhood": "Jamaica Plain",
    "price": 220,
    "rating": 4.98,
    "reviewCount": 78,
    "host": {
      "bio": "As a local runner, I can guide you to the best shakeout routes and post-race recovery spots in Jamaica Plain.",
      "name": "Liam",
      "badge": "Boston Marathon Finisher",
      "avatar": "L",
      "avatarUrl": "https://i.pravatar.cc/96?img=35"
    },
    "images": [
      {
        "alt": "Comfortable Retreat for Boston Marathon Runners — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/runners/boston-ma-comfortable-retreat-kabz-0.png"
      }
    ],
    "tags": [
      "Running Route",
      "Local Insights",
      "Race Logistics"
    ],
    "amenities": [
      "Private Room",
      "Full Kitchen",
      "On-site Parking"
    ],
    "highlight": "Just a short jog to the Emerald Necklace trails, perfect for warm-ups and cool-downs.",
    "description": "This Jamaica Plain apartment provides straightforward access to the Emerald Necklace trails, ideal for warm-ups and cool-downs. With local cafes nearby for fueling up and public transport options to the marathon starting line, your stay is streamlined for race day. Your host, familiar with the area, is ready to share helpful tips for an efficient preparation."
  },
  {
    "id": "chicago-il-runners-retreat-gc4b",
    "tenant": "runners",
    "bookingMode": "native",
    "title": "Lincoln Park apartment steps from Lakefront Trail for runners",
    "location": "Chicago, IL",
    "neighborhood": "Lincoln Park",
    "price": 220,
    "rating": 4.95,
    "reviewCount": 86,
    "host": {
      "bio": "I’m a local runner and love sharing tips on the best routes and local food for race week.",
      "name": "Elena",
      "badge": "Chicago Marathon Ambassador",
      "avatar": "E",
      "avatarUrl": "https://i.pravatar.cc/96?img=2"
    },
    "images": [
      {
        "alt": "Runners’ Retreat Near the Chicago Marathon — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/runners/chicago-il-runners-retreat-gc4b-0.png"
      }
    ],
    "tags": [
      "Marathon-friendly",
      "Local insights",
      "Shakeout runs"
    ],
    "amenities": [
      "Quiet workspace",
      "Kitchen for meal prep",
      "Private bathroom"
    ],
    "highlight": "Steps away from Lakefront Trail, perfect for your pre-race shakeout.",
    "description": "This Lincoln Park apartment offers direct access to the Lakefront Trail, ideal for your pre-race shakeout runs. Enjoy a quiet environment where you can recharge, and benefit from local dining recommendations and logistical support. With an eye for runners' needs, I can help make your stay smooth and focused."
  },
  {
    "id": "harper-s-ferry-wv-cozy-cabin-qqch",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "Historic District cabin steps from Maryland Heights trailhead",
    "location": "Harper's Ferry, WV",
    "neighborhood": "Historic District",
    "price": 180,
    "rating": 4.96,
    "reviewCount": 29,
    "host": {
      "bio": "An avid hiker who has explored every inch of the local trail system, ready to share tips and hidden gems.",
      "name": "Liam",
      "badge": "Appalachian Trail Specialist",
      "avatar": "L",
      "avatarUrl": "https://i.pravatar.cc/96?img=7"
    },
    "images": [
      {
        "alt": "Cozy Cabin Near the Appalachian Trail — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/hikers/harper-s-ferry-wv-cozy-cabin-qqch-0.png"
      }
    ],
    "tags": [
      "Cabin Retreat",
      "Trail Access",
      "Local Insights"
    ],
    "amenities": [
      "Gear rental",
      "Maps and guides",
      "Firepit"
    ],
    "highlight": "Steps away from the iconic Maryland Heights trailhead.",
    "description": "This cabin in the Historic District of Harper's Ferry serves as a practical launch point for your adventures on the Appalachian Trail, just steps from the iconic Maryland Heights trailhead. Liam offers valuable local insights and is happy to share gear, ensuring your hiking experience is smooth and enjoyable. After a day's exploration, unwind around the firepit, taking a moment to appreciate the stunning surroundings you've discovered.",
    "gear": [
      {
        "id": "poles",
        "icon": "poles",
        "name": "Trekking poles",
        "category": "Trail support",
        "quantity": 2
      },
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      }
    ]
  },
  {
    "id": "conway-nh-rustic-retreat-spfx",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "White Mountains cabin with sunset views of Mount Washington",
    "location": "Conway, NH",
    "neighborhood": "White Mountains",
    "price": 185,
    "rating": 4.9,
    "reviewCount": 89,
    "host": {
      "bio": "I’ve led dozens of backpacking trips in the White Mountains and love sharing my trail insights with guests.",
      "name": "Sara",
      "badge": "Certified Wilderness Guide",
      "avatar": "S",
      "avatarUrl": "https://i.pravatar.cc/96?img=30"
    },
    "images": [
      {
        "alt": "Rustic Retreat Overlooking Mount Washington — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/hikers/conway-nh-rustic-retreat-spfx-0.png"
      }
    ],
    "tags": [
      "Hiking Access",
      "Local Guide",
      "Nature Retreat"
    ],
    "amenities": [
      "Trail Maps",
      "Camp Kitchen",
      "Gear Rental"
    ],
    "highlight": "Stunning views of Mount Washington from the porch at sunset.",
    "description": "This rustic cabin offers direct views of Mount Washington, particularly stunning at sunset from the porch. It serves as a practical base for hikers eager to explore the region's trails, with Sara ready to share her expertise on local hikes and nearby lakes.",
    "gear": [
      {
        "id": "poles",
        "icon": "poles",
        "name": "Trekking poles",
        "category": "Trail support",
        "quantity": 2
      },
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      }
    ]
  },
  {
    "id": "whitefish-mt-charming-cabin-l0ds",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "Columbia Falls cabin with direct access to 700 miles of trails",
    "location": "Whitefish, MT",
    "neighborhood": "Columbia Falls",
    "price": 220,
    "rating": 4.92,
    "reviewCount": 107,
    "host": {
      "bio": "I love sharing the trails of Glacier, where I’ve spent countless weekends hiking and exploring.",
      "name": "Jess",
      "badge": "Certified Wilderness Instructor",
      "avatar": "J",
      "avatarUrl": "https://i.pravatar.cc/96?img=16"
    },
    "images": [
      {
        "alt": "Charming Cabin Steps from Glacier National Park — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/hikers/whitefish-mt-charming-cabin-l0ds-0.png"
      }
    ],
    "tags": [
      "Hiking Haven",
      "Trail Access",
      "Gear Share"
    ],
    "amenities": [
      "Hiking gear available",
      "Firepit for evenings",
      "Local guidebook collection"
    ],
    "highlight": "Direct access to over 700 miles of trails just outside your door.",
    "description": "This cabin in the woods near Columbia Falls offers direct access to over 700 miles of trails, making it a practical choice for your Glacier National Park excursions. Your host provides trail maps and weather updates, as well as gear to borrow, helping you to easily plan your hiking adventures. After a day on the trails, enjoy the tranquility of the surroundings and unwind by a warm fire.",
    "gear": [
      {
        "id": "poles",
        "icon": "poles",
        "name": "Trekking poles",
        "category": "Trail support",
        "quantity": 2
      },
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      },
      {
        "id": "gps",
        "icon": "gps",
        "name": "Satellite GPS",
        "category": "Navigation",
        "quantity": 1
      }
    ]
  },
  {
    "id": "enumclaw-wa-cozy-stay-kpwe",
    "tenant": "hikers",
    "bookingMode": "native",
    "title": "Enumclaw cabin close to Sunrise Visitor Center trails",
    "location": "Enumclaw, WA",
    "neighborhood": "Near Crystal Mountain",
    "price": 180,
    "rating": 4.88,
    "reviewCount": 49,
    "host": {
      "bio": "I love sharing local trails and hidden gems near Mount Rainier.",
      "name": "Jessica",
      "badge": "National Park Guide",
      "avatar": "J",
      "avatarUrl": "https://i.pravatar.cc/96?img=28"
    },
    "images": [
      {
        "alt": "Cozy Stay for Mount Rainier Adventurers — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/hikers/enumclaw-wa-cozy-stay-kpwe-0.png"
      }
    ],
    "tags": [
      "Mountains",
      "Hiking",
      "Nature"
    ],
    "amenities": [
      "Trail maps",
      "Backpacking gear to borrow",
      "Coffee bar"
    ],
    "highlight": "Just a short drive to the stunning Sunrise Visitor Center for breathtaking views.",
    "description": "This cabin offers a serene retreat after a day exploring the trails around Mount Rainier. With easy access to the Sunrise Visitor Center, you can count on helpful trail recommendations and real-time updates on conditions from a local host who knows the area well. Take a moment to sip on freshly brewed coffee and share experiences with fellow guests as you unwind.",
    "gear": [
      {
        "id": "poles",
        "icon": "poles",
        "name": "Trekking poles",
        "category": "Trail support",
        "quantity": 2
      },
      {
        "id": "bear-canister",
        "icon": "canister",
        "name": "Bear canister",
        "category": "Food safety",
        "quantity": 1
      },
      {
        "id": "gps",
        "icon": "gps",
        "name": "Satellite GPS",
        "category": "Navigation",
        "quantity": 1
      },
      {
        "id": "stove",
        "icon": "stove",
        "name": "Compact stove",
        "category": "Camp kitchen",
        "quantity": 1
      }
    ]
  },
  {
    "id": "bend-or-charming-cabin-4equ",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "Cabin with sunset views and climbing gear near Smith Rock",
    "location": "Bend, OR",
    "neighborhood": "Smith Rock State Park",
    "price": 180,
    "rating": 4.89,
    "reviewCount": 96,
    "host": {
      "bio": "I’ve been climbing these routes for over a decade and love sharing my local insights with newcomers.",
      "name": "Rachel",
      "badge": "Climbing guide",
      "avatar": "R",
      "avatarUrl": "https://i.pravatar.cc/96?img=8"
    },
    "images": [
      {
        "alt": "Charming Cabin by Smith Rock — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/bend-or-charming-cabin-4equ-0.png"
      }
    ],
    "tags": [
      "climbing-friendly",
      "local insights",
      "gear-lending"
    ],
    "amenities": [
      "gear storage",
      "kitchen access",
      "espresso machine"
    ],
    "highlight": "Enjoy morning coffee with breathtaking views of Smith Rock.",
    "description": "This cabin offers a straightforward and comfortable place to rest after a day of climbing at Smith Rock. Enjoy your morning coffee while taking in stunning views of the canyon, and unwind in the evening on the patio as the sun sets. Your host, knowledgeable about local routes, can share insights and provides climbing gear for those in need.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      }
    ]
  },
  {
    "id": "fayetteville-wv-relax-in-40mk",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "New River Gorge home near classic climbs like The Endless Wall",
    "location": "Fayetteville, WV",
    "neighborhood": "New River Gorge",
    "price": 195,
    "rating": 4.91,
    "reviewCount": 105,
    "host": {
      "bio": "Jenna knows the ins and outs of the New River Gorge, from crag beta to the best local coffee spots.",
      "name": "Jenna",
      "badge": "Competitive Climber",
      "avatar": "J",
      "avatarUrl": "https://i.pravatar.cc/96?img=44"
    },
    "images": [
      {
        "alt": "Relax in a Climber's Haven by the New River Gorge — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/fayetteville-wv-relax-in-40mk-0.png"
      }
    ],
    "tags": [
      "Climbing Gear",
      "Local Knowledge",
      "Close to Crags"
    ],
    "amenities": [
      "Climbing gear rentals",
      "Coffee maker for early starts",
      "Fire pit for evenings"
    ],
    "highlight": "Just minutes from classic climbs like The Endless Wall and The Leap.",
    "description": "This home offers easy access to classic climbs such as The Endless Wall and The Leap, making it a convenient base for climbers. Your host, Jenna, is well-acquainted with the local crags and can provide valuable recommendations, along with lending climbing gear. After a day of climbing, gather around the warmth of the fire pit to unwind and share stories.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      }
    ]
  },
  {
    "id": "bend-or-cozy-mountain-nedo",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "Sisters cabin with breakfast views over the Crooked River",
    "location": "Bend, OR",
    "neighborhood": "Sisters",
    "price": 180,
    "rating": 4.94,
    "reviewCount": 68,
    "host": {
      "bio": "I'm a local climbing guide with an intimate understanding of Smith Rock's hidden gems and routes.",
      "name": "Jamie",
      "badge": "Climbing guide",
      "avatar": "J",
      "avatarUrl": "https://i.pravatar.cc/96?img=46"
    },
    "images": [
      {
        "alt": "Cozy Mountain Retreat near Smith Rock — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/bend-or-cozy-mountain-nedo-0.png"
      }
    ],
    "tags": [
      "Climbing",
      "Outdoor",
      "Local Insider"
    ],
    "amenities": [
      "Gear lending",
      "Laundry facilities",
      "Early check-in"
    ],
    "highlight": "Start your day with a trail breakfast overlooking the Crooked River.",
    "description": "Start your day with breakfast views of the Crooked River from this cabin, conveniently close to Smith Rock State Park for climbers. Jamie, your knowledgeable host, can guide you to routes suited to your skill level and lend equipment to make your adventure easier. After a day outdoors, return to a tranquil retreat, designed for comfort and relaxation.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      }
    ]
  },
  {
    "id": "slade-ky-cozy-cottage-n0v7",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "Cottage near sandstone cliffs with climbing insights and gear rental",
    "location": "Slade, KY",
    "neighborhood": "Red River Gorge",
    "price": 170,
    "rating": 4.95,
    "reviewCount": 81,
    "host": {
      "bio": "As a local guide and climber, I love sharing the best routes and hidden gems of the Gorge with fellow enthusiasts.",
      "name": "Anna",
      "badge": "Local climbing guide",
      "avatar": "A",
      "avatarUrl": "https://i.pravatar.cc/96?img=9"
    },
    "images": [
      {
        "alt": "Cozy Cottage Steps from Red River Gorge — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/slade-ky-cozy-cottage-n0v7-0.png"
      }
    ],
    "tags": [
      "climbing",
      "outdoors",
      "gear rental"
    ],
    "amenities": [
      "climbing gear rental",
      "coffee maker",
      "outdoor fire pit"
    ],
    "highlight": "Just a short drive to the famous sandstone cliffs of Red River Gorge.",
    "description": "A practical base for climbers, this cottage is only a short drive from the renowned sandstone cliffs of Red River Gorge. Here, you'll find personalized climbing insights and access to gear rental, ensuring you're well-equipped for your adventures. The host is familiar with the area and can provide guidance tailored to your climbing goals.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      },
      {
        "id": "crash-pad",
        "icon": "pack",
        "name": "Bouldering crash pad",
        "category": "Bouldering",
        "quantity": 1
      }
    ]
  },
  {
    "id": "joshua-tree-ca-cozy-rock-eccy",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "Joshua Tree space stocked with climbing gear near Hidden Valley",
    "location": "Joshua Tree, CA",
    "neighborhood": "Near Hidden Valley",
    "price": 180,
    "rating": 4.92,
    "reviewCount": 96,
    "host": {
      "bio": "I’ve been climbing these desert rocks for over a decade and love sharing my favorite spots.",
      "name": "Maddie",
      "badge": "Climbing guide",
      "avatar": "M",
      "avatarUrl": "https://i.pravatar.cc/96?img=21"
    },
    "images": [
      {
        "alt": "Cozy Rock Climber's Retreat in Joshua Tree — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/joshua-tree-ca-cozy-rock-eccy-0.png"
      }
    ],
    "tags": [
      "Climbing",
      "Desert",
      "Adventure"
    ],
    "amenities": [
      "Climbing gear rental",
      "Coffee bar",
      "Outdoor fire pit"
    ],
    "highlight": "Just minutes from the best bouldering in the park.",
    "description": "This welcoming space is just minutes from the premier bouldering at Hidden Valley, providing easy access for climbers looking to maximize their time on the rock. Stocked with essential climbing gear and ropes for guests to borrow, the property makes it simple to prepare for your adventures. After a day of climbing, enjoy a relaxed evening around the fire pit, sharing stories and camaraderie.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      },
      {
        "id": "crash-pad",
        "icon": "pack",
        "name": "Bouldering crash pad",
        "category": "Bouldering",
        "quantity": 1
      },
      {
        "id": "quickdraws",
        "icon": "rope",
        "name": "Quickdraw set",
        "category": "Sport rack",
        "quantity": 1
      }
    ]
  },
  {
    "id": "joshua-tree-ca-comfortable-hostel-ywmo",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "Joshua Tree bunkhouse steps from climbing routes",
    "location": "Joshua Tree, CA",
    "neighborhood": "Joshua Tree Village",
    "price": 220,
    "rating": 4.95,
    "reviewCount": 63,
    "host": {
      "bio": "A local climbing coach who knows the best routes and secret gems.",
      "name": "Anna",
      "badge": "Climbing Coach",
      "avatar": "A",
      "avatarUrl": "https://i.pravatar.cc/96?img=69"
    },
    "images": [
      {
        "alt": "Comfortable Hostel-Style Bunkhouse Near Joshua Tree — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/joshua-tree-ca-comfortable-hostel-ywmo-0.png"
      }
    ],
    "tags": [
      "Climbing Community",
      "Outdoor Equipment",
      "Cozy Stay"
    ],
    "amenities": [
      "Coffee maker",
      "Climbing gear rental",
      "Shared kitchen"
    ],
    "highlight": "Enjoy a sunrise approach to your next favorite route, just minutes away.",
    "description": "Just a few minutes from the climbing routes, this bunkhouse serves as a welcoming spot for climbers to unwind after a day on the rock. It has a fully equipped kitchen for meal preparation and arrangements for rental of climbing gear, ensuring you have all the essentials for enjoying your time in Joshua Tree.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      },
      {
        "id": "crash-pad",
        "icon": "pack",
        "name": "Bouldering crash pad",
        "category": "Bouldering",
        "quantity": 1
      }
    ]
  },
  {
    "id": "slade-ky-warm-cabin-jhf5",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "Red River Gorge cabin with quick access to climbing routes",
    "location": "Slade, KY",
    "neighborhood": "Red River Gorge",
    "price": 180,
    "rating": 4.92,
    "reviewCount": 77,
    "host": {
      "bio": "I'm an avid climber and local guide with years of experience exploring these cliffs.",
      "name": "Megan",
      "badge": "Red River Routes Expert",
      "avatar": "M",
      "avatarUrl": "https://i.pravatar.cc/96?img=11"
    },
    "images": [
      {
        "alt": "Warm Cabin Steps from Red River Gorge Crags — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/slade-ky-warm-cabin-jhf5-0.png"
      }
    ],
    "tags": [
      "Climbing",
      "Nature",
      "Outdoor Enthusiast"
    ],
    "amenities": [
      "Climbing gear rental",
      "Full kitchen",
      "Fire pit"
    ],
    "highlight": "Quick access to over 1,000 climbing routes in stunning sandstone.",
    "description": "This cabin provides essential comforts after a day spent on the climbing routes of Red River Gorge. You'll find local climbing gear available for use, along with guidance on the area's climbing options to help you explore over 1,000 routes. Its serene setting ensures a restful night, allowing you to recharge for your next adventure.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      },
      {
        "id": "crash-pad",
        "icon": "pack",
        "name": "Bouldering crash pad",
        "category": "Bouldering",
        "quantity": 1
      },
      {
        "id": "quickdraws",
        "icon": "rope",
        "name": "Quickdraw set",
        "category": "Sport rack",
        "quantity": 1
      }
    ]
  },
  {
    "id": "slade-ky-cozy-base-nhl5",
    "tenant": "climbers",
    "bookingMode": "native",
    "title": "Slade cabin steps from the best trad routes in Red River Gorge",
    "location": "Slade, KY",
    "neighborhood": "Red River Gorge",
    "price": 199,
    "rating": 4.99,
    "reviewCount": 32,
    "host": {
      "bio": "As a local climbing guide, I know every route and secret crag in the Gorge.",
      "name": "Emma",
      "badge": "Climbing guide",
      "avatar": "E",
      "avatarUrl": "https://i.pravatar.cc/96?img=52"
    },
    "images": [
      {
        "alt": "Cozy Base for Red River Gorge Climbers — view 1",
        "src": "https://rntovnujtyhmdnkeljny.supabase.co/storage/v1/object/public/listing-images/climbers/slade-ky-cozy-base-nhl5-0.png"
      }
    ],
    "tags": [
      "Climbing",
      "Gear lending",
      "Local insights"
    ],
    "amenities": [
      "Climbing gear available",
      "Early breakfast options",
      "Heated drying rack"
    ],
    "highlight": "Steps from the best trad routes in the area.",
    "description": "A practical stay that places you moments away from the best traditional climbing routes in Red River Gorge. You'll find gear available to lend and valuable local insights to enhance your climbing experience. After your day on the cliffs, the cabin provides a straightforward, restful environment tailored for climbers.",
    "gear": [
      {
        "id": "rope",
        "icon": "rope",
        "name": "Dynamic climbing rope (60m)",
        "category": "Protection",
        "quantity": 1
      },
      {
        "id": "harness",
        "icon": "harness",
        "name": "Harness + belay device",
        "category": "Protection",
        "quantity": 2
      },
      {
        "id": "helmet",
        "icon": "helmet",
        "name": "Climbing helmet",
        "category": "Safety",
        "quantity": 2
      },
      {
        "id": "crash-pad",
        "icon": "pack",
        "name": "Bouldering crash pad",
        "category": "Bouldering",
        "quantity": 1
      },
      {
        "id": "quickdraws",
        "icon": "rope",
        "name": "Quickdraw set",
        "category": "Sport rack",
        "quantity": 1
      }
    ]
  }
]
